name: Atualizar estatísticas do perfil

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  gerar-estatisticas:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Gerar cartões do GitHub
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: -3
          AUTO_PUSH: true
          THEME: radical
          ANIMATION: load
          DURATION: 3
